import './globals.css'
import type {GetStaticProps, Metadata} from 'next'
import {Inter} from 'next/font/google'
import {initializeStore} from "@stores/rootStore";
import {SessionProvider, useSession} from "next-auth/react";
import {Component} from "preact/debug/src/internal";
import {getServerSession} from "next-auth";
import {authOptions} from "@lib/auth";
import {NextAuthProvider} from "@app/providers";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export const getStaticProps: GetStaticProps = async () => {
    const rootStore = initializeStore()

    return {props: {rootStore}}
}

function Auth({ children }) {
    // if `{ required: true }` is supplied, `status` can only be "loading" or "authenticated"
    const { status } = useSession({ required: true })

    if (status === "loading") {
        return <div>Loading...</div>
    }

    return children
}

export default function RootLayout({children}: { children: React.ReactNode }) {

    return (
        <html lang="en">
            <body>
                <NextAuthProvider>
                    {children}

                </NextAuthProvider>
            </body>
        </html>
    )
}
